In [2]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
sum = np.add(x,y)
print(sum)

[5 7 9]


In [ ]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
sum = np.add(x,y)
print(sum)

[5 7 9]


In [ ]:
print(np.log(sum))

[1.60943791 1.94591015 2.19722458]


In [ ]:
arr_power = np.power(sum, 2)
print(arr_power)
print(np.exp(x))

[25 49 81]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
#comparison and logical UFuncs
arr_2d = np.array([[2,6,8],
              [10,12,14],
              [16,18,20]])
cond1 = arr_2d >8
cond2 = arr_2d <15
print(cond1)
print("\n", cond2)
print("\n", np.logical_and(cond1,cond2))

[[False False False]
 [ True  True  True]
 [ True  True  True]]

 [[ True  True  True]
 [ True  True  True]
 [False False False]]

 [[False False False]
 [ True  True  True]
 [False False False]]


In [ ]:
#Broadcasting
arr_b= np.array([2,4,6])
print(arr_b + 10)

[12 14 16]


In [ ]:
#Linear algebra
A = np.array([[2,4],
              [6,8]])
B = np.array([[3,6],
              [9,12]])
print("Matrix Multiplication \n", A @ B)
print("\nInverse of A", np.linalg.inv(A))


Matrix Multiplication 
 [[ 42  60]
 [ 90 132]]

Inverse of A [[-1.    0.5 ]
 [ 0.75 -0.25]]


In [3]:
print(np.log(sum))

[1.60943791 1.94591015 2.19722458]


In [8]:
arr_power = np.power(sum, 2)
print(arr_power)
print(np.exp(x))

[25 49 81]
[ 2.71828183  7.3890561  20.08553692]


In [12]:
#comparison and logical UFuncs
arr_2d = np.array([[2,6,8],
              [10,12,14],
              [16,18,20]])
cond1 = arr_2d >8
cond2 = arr_2d <15
print(cond1)
print("\n", cond2)
print("\n", np.logical_and(cond1,cond2))

[[False False False]
 [ True  True  True]
 [ True  True  True]]

 [[ True  True  True]
 [ True  True  True]
 [False False False]]

 [[False False False]
 [ True  True  True]
 [False False False]]


In [13]:
#Broadcasting
arr_b= np.array([2,4,6])
print(arr_b + 10)

[12 14 16]
